services:
  tea-sprint:
    image: sairash/tea-sprint
    container_name: tea-sprint
    hostname: tea-sprint
    restart: unless-stopped
    ports:
      - "1706:1706"
    volumes:
      - ./config.ini:/usr/src/app/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/www:/srv/www